apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rtmp-relay
  name: rtmp-relay
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rtmp-relay
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rtmp-relay
    spec:
      containers:
      - env:
        - name: INGRESS_SUBNETS
          value: "172.16.16.0/24"
        - name: INGRESS_STREAM_KEY
          valueFrom:
            secretKeyRef:
              name: rtmp-relay
              key: ingress-stream-key
        - name: PUSH_RTMP_URL
          valueFrom:
            secretKeyRef:
              name: rtmp-relay
              key: push-rtmp-url
        image: icydoge/web:rtmp-relay-3320c14
        imagePullPolicy: IfNotPresent
        name: rtmp-relay
        ports:
        - containerPort: 1935
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 3000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 1024Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# Intended for use of MetalLB to create relatively fixed internal IP
# for access from a VPN subnet
apiVersion: v1
kind: Service
metadata:
  name: rtmp-relay-ingress
  namespace: default
spec:
  ports:
  - name: rtmp
    nodePort: 31935
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: rtmp-relay
  type: LoadBalancer
---
# For stream stat monitoring from internal network
apiVersion: v1
kind: Service
metadata:
  name: rtmp-relay-http
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rtmp-relay
  sessionAffinity: None
  type: ClusterIP